### ISSUE TITLE
Gump Scaling & Opacity

### ISSUE THREAD

**Issue by UltimaScripts** [jsebold666/TazUO#112]
So some of us UO players don't have the best eye sight. It can be difficult to see the smaller elements on gumps/windows/guis etc

I'd like an option that found every gump on screen and provided a way to scale it's size and in some cases set it's opacity.

I've tried using windows DPI and lower screen resolutions but the former affects everything and the latter causes my monitor to act weird.

Here is an example of options that is generated/filled with existing gumps on screen.
https://i.imgur.com/ij35Lmp.png

**Comment by bittiez** [comment]
So this is something I could work towards eventually, but the way CUO was designed this would mean going through each gump one by one and adding scaling to everything in that gump which would be a fairly large undertaking
