### ISSUE TITLE
Equipment color display doesn't work

### ISSUE THREAD

**Issue by nbyaya** [jsebold666/TazUO#229]
**Describe the bug**

Equipment color display doesn't work

**Screenshots**
![image](https://github.com/bittiez/TazUO/assets/49419718/2057fe0b-3a2a-44bf-92b3-38dec627374f)

The correct display should read

![image](https://github.com/bittiez/TazUO/assets/49419718/9d0dd163-c6e3-462c-be50-c19af63ab29b)

**Comment by nbyaya** [comment]
![image](https://github.com/bittiez/TazUO/assets/49419718/a4c3588a-e641-4710-928b-21941b646ee1)

**Comment by bittiez** [comment]
https://github.com/jsebold666/TazUO/pull/249
