### ISSUE TITLE
Nothing happens when click play and on the latest UO client

### ISSUE THREAD

**Issue by GolgothaX** [jsebold666/TazUO#236]
**Describe the bug**
Nothing happens when clicking play.

**To Reproduce**
1. Install the latest OSI client (7.0.104.0 or newer)
2. If needed, install TazUO and TazUO Launcher
3. If needed, configure TazUO
4. Choose your profile and press "Play"

**Expected behavior**
UO should luanch.

Probably fixed by this PR in ClassicUO
https://github.com/ClassicUO/ClassicUO/pull/1699

**Comment by jsebold666** [comment]
@GolgothaX 
It wouldn't just be this MR, there are several others that still need to be implemented to run the 104 client.
We're still working on it, but I'm seeing new Karasho versions that don't work at all.
